services:
  - name: real-estate-backend
    type: web
    env: go
    build:
      cmd: go build -o main ./backend/cmd
    start:
      cmd: ./main
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_URI
        value: "mongodb+srv://SoeelBeg:SOEELbeg@cluster0.qmoic.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

  - name: real-estate-frontend
    type: static
    env: static
    build:
      cmd: npm install && npm run build
    staticPublishPath: ./frontend
