services:
  - type: web
    name: real-estate-backend
    env: go
    buildCommand: "go build -o main ./backend/cmd/main.go"
    startCommand: "./main"
    region: oregon
    envVars:
      - key: PORT
        value: "8000"  # Render automatically assigns a dynamic port, default is 8000

databases:
  - type: mongo
    name: realestate
    region: oregon
    connectionURI: mongodb+srv://SoeelBeg:SOEELbeg@cluster0.qmoic.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
