services:
  - type: web
    name: real-estate-app
    env: go
    buildCommand: "go build -o app ./backend/cmd/main.go"
    startCommand: "./app"
    region: oregon
    envVars:
      - key: PORT
        value: "8000"  # Render assigns a dynamic port, default is 8000

databases:
  - type: mongo
    name: realestate
    region: oregon
    connectionURI: mongodb+srv://SoeelBeg:SOEELbeg@cluster0.qmoic.mongodb.net/?retryWrites=true&w=majority
